Upgrade to the latest pyproject-flake8 to fix https://github.com/csachs/pyproject-flake8/issues/13
`tox -e lint` fails with AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'.